<a href="https://colab.research.google.com/github/pafernannapi18/GithubIntro/blob/main/19th_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## [Problem 1] Scratch of train_test_split​

In [8]:
import numpy as np 
from sklearn.model_selection import train_test_split
def scratch_train_test_split(X, y, train_size=0.8, seed=0):
  
 
  np.random.seed(seed)
  np.random.shuffle(X)

  np.random.seed(seed)
  np.random.shuffle(y)

  X_elements = len(X)
  y_elements = len(y)

  X_split = int(X_elements*train_size)
  y_split = int(y_elements*train_size)

  X_train, X_test = X[:X_split], X[X_split:]
  y_train, y_test = y[:y_split], y[y_split:]

  return X_train, X_test, y_train, y_test


In [9]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X, y, train_size= 0.8)

print(X_train)
print(y_train)

[[2 2 2]
 [0 0 0]
 [1 1 1]
 [3 3 3]]
[2 0 1 3]


In [10]:
print(X_test)
print(y_test)

[[4 4 4]]
[4]


In [11]:
X = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
y = np.array([0, 1, 2, 3, 4])
X.shape, y.shape

((5, 3), (5,))

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)
print(X_train)
print(y_train)

[[2 2 2]
 [1 1 1]
 [4 4 4]
 [3 3 3]]
[2 1 4 3]


In [13]:
print(X_test)
print(y_test)

[[0 0 0]]
[0]


## [Problem 2] Creating a code to solve the classification problem


In [14]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import  StandardScaler
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import SGDRegressor
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [15]:
iris_dataset = load_iris()
columns_list = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
df = pd.DataFrame(iris_dataset['data'], columns= columns_list)
df['target'] = iris_dataset['target']
df = df[df['target'] != 0]
df

sepal_length  sepal_width  petal_length  petal_width  target
50            7.0          3.2           4.7          1.4       1
51            6.4          3.2           4.5          1.5       1
52            6.9          3.1           4.9          1.5       1
53            5.5          2.3           4.0          1.3       1
54            6.5          2.8           4.6          1.5       1
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[100 rows x 5 columns]

In [16]:
X1 = df.drop(['target'], axis=1)
y1 = df.target
X1.shape, y1.shape

((100, 4), (100,))

In [17]:
X1 = X1.to_numpy()
y1 = y1.to_numpy()

Sample DataSet 1

In [18]:
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0, 0.8], [0.8, 1.0]]
f0 = np.random.multivariate_normal(f0, cov, int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))
X = np.concatenate((f0, f1))
y = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2)))*(-1))).astype(np.int)
random_index = np.random.permutation(np.arange(n_samples))
X2 = X[random_index]
y2 = y[random_index]
X2.shape, y2.shape

((500, 2), (500,))

Sample DataSet 2

In [19]:
X3 = np.array([
    [-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
    [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
    [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
    [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
    [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
    [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
    [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
    [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
    [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
    [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
    [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
    [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
    [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
    [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
    [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
    [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
    [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
    [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
    [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
    [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ],
])
y3 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
X3.shape, y3.shape

((40, 2), (40,))

Division of Training Data and Verification Data

In [20]:
X1_train, X1_test, y1_train, y1_test = scratch_train_test_split(X1, y1, train_size=0.8)

X2_train, X2_test, y2_train, y2_test = scratch_train_test_split(X2, y2, train_size=0.8)

X3_train, X3_test, y3_train, y3_test = scratch_train_test_split(X3, y3, train_size=0.8)

Preprocessing/Standardization

In [21]:
scaler = StandardScaler()

scaler.fit(X1_train)
X1_train = scaler.transform(X1_train)
X1_test = scaler.transform(X1_test)

scaler.fit(X2_train)
X2_train = scaler.transform(X2_train)
X2_test = scaler.transform(X2_test)

scaler.fit(X3_train)
X3_train = scaler.transform(X3_train)
X3_test = scaler.transform(X3_test)

Learning and Estimation

SGD


Iris Data Set

In [22]:
sdg1 = SGDClassifier(loss='log')
sdg1.fit(X1_train, y1_train)
y_preds1 =sdg1.predict(X1_test)

In [23]:
y_preds1 

array([1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1])

In [24]:
sdg1.score(X1_test, y1_test) 

0.95

DataSet 1

In [25]:
sgd2 = SGDClassifier(loss='log')
sgd2.fit(X2_train, y2_train)
y_preds2 = sgd2.predict(X2_test)

In [26]:
y_preds2

array([-1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1,  1, -1,  1,  1, -1, -1,
        1, -1, -1, -1, -1,  1, -1,  1,  1, -1, -1,  1,  1,  1, -1, -1,  1,
       -1, -1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1,  1, -1, -1, -1,
       -1,  1,  1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1,  1, -1,
       -1,  1,  1,  1, -1,  1, -1, -1, -1,  1,  1, -1,  1,  1, -1])

In [27]:
sgd2.score(X2_test, y2_test)

1.0

DataSet 2

In [28]:
sgd3 = SGDClassifier(loss='log')
sgd3.fit(X3_train, y3_train)
y_preds3 = sgd3.predict(X3_test)

In [29]:
y_preds3

array([0, 1, 0, 0, 0, 1, 0, 0])

In [30]:
sgd3.score(X3_test, y3_test)

0.875

SVM


Iris DataSet




In [31]:
svc1 = SVC()
svc1.fit(X1_train, y1_train)
y_preds4 = svc1.predict(X1_test)

In [32]:
svc1.score(X1_test, y1_test)

0.95

DataSet 1

In [33]:
svc2 = SVC()
svc2.fit(X2_train, y2_train)
y_preds5 = svc2.predict(X2_test)

In [34]:
svc2.score(X2_test, y2_test)

1.0

Decision Tree


Iris DataSet



In [35]:
dt1 = DecisionTreeClassifier()
dt1.fit(X1_train, y1_train)
y_preds7 = dt1.predict(X1_test)

In [36]:
dt1.score(X1_test, y1_test)

0.9

DataSet 1

In [37]:
dt2 = DecisionTreeClassifier()
dt2.fit(X2_train, y2_train)
y_preds8 = dt2.predict(X2_test)

In [38]:
dt2.score(X2_test, y2_test)

1.0

DataSet 2

In [39]:
dt3 = DecisionTreeClassifier()
dt3.fit(X3_train, y3_train)
y_preds9 = dt3.predict(X3_test)

In [40]:
dt3.score(X3_test, y3_test)

1.0

## [Problem 3] Creating a code to solve the regression problem

In [41]:
trains = pd.read_csv('/content/drive/MyDrive/Train dataset/train.csv')
X4 = trains.loc[:,['GrLivArea', 'YearBuilt']]
y4 = trains.loc[:, 'SalePrice']

X4 = X4.to_numpy()
y4 = y4.to_numpy()

X4.shape, y4.shape

((1460, 2), (1460,))

In [42]:
X4_train, X4_test, y4_train, y4_test = scratch_train_test_split(X4, y4, train_size=0.8)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(X4_train)
X4_train = scaler.transform(X4_train)
X4_test = scaler.transform(X4_test)

SGD

In [43]:
reg1 = SGDRegressor()
reg1.fit(X4_train, y4_train)
y_preds10 = reg1.predict(X4_test)

In [44]:
reg1.score(X4_test, y4_test)

0.6499209662086336

In [45]:
from sklearn.metrics import mean_squared_error

mse1 = mean_squared_error(y4_test, y_preds10)
print('MSE SGD: {:,.3f}'.format(mse1))

MSE SGD: 1,724,280,326.017


SVM

In [46]:
from sklearn.svm import SVR

reg2 = SVR()
reg2.fit(X4_train, y4_train)
y_preds11 = reg2.predict(X4_test)

In [47]:
reg2.score(X4_test, y4_test)

-0.003402281129969209

In [48]:
mse2 = mean_squared_error(y4_test, y_preds11)
print('MSE SGD: {:,.3f}'.format(mse2))

MSE SGD: 4,942,160,613.549


DecisionTree

In [49]:
reg3 = DecisionTreeClassifier()
reg3.fit(X4_train, y4_train)
y_preds12 = reg3.predict(X4_test)

In [50]:
reg3.score(X4_test, y4_test)

0.00684931506849315

In [51]:
mse3 = mean_squared_error(y4_test, y_preds12)
print('MSE SGD: {:,.3f}'.format(mse3))

MSE SGD: 2,728,788,757.257
